import {NAME} from './constants';

export const FETCH_FORECAST_REQUEST = `${NAME}/FETCH_FORECAST_REQUEST`;
export const FETCH_FORECAST_SUCCESS = `${NAME}/FETCH_FORECAST_SUCCESS`;
export const FETCH_FORECAST_FAILURE = `${NAME}/FETCH_FORECAST_FAILURE`;

export const SET_SELECTED_DATE = `${NAME}/SET_SELECTED_DATE`;
